openapi: 3.0.2
info:
  version: 1.0.0
  title: Métodos de la API del Almacen
  description: Se describen los métodos y que tipo de recursos nos ofrece en cada ruta de la API del Almacen.
servers:
  - url: http://localhost:5000/api/almacen
  - url: http://127.0.0.1:5000/api/almacen
tags:
  - name: Almacen
    description: Se detallan los métodos y recursos del almacen que hay en esta API.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: consumidor_pan 
security:
- ApiKeyAuth: []  
paths:
  /tabla:
    post:
      tags:
        - Almacen
      summary: Crearemos la tabla en nuestra base de datos.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Tabla creada
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
    delete:
      tags:
        - Almacen
      summary: Eliminaremos la tabla de nuestra base de datos.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Tabla eliminada
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
  /producto:
    get:
      tags:
        - Almacen
      summary: Veremos todos los productos que hay en la tabla.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: number
                    description: Id
                    example: 1
                  name:
                    type: string
                    description: Nombre del producto
                    example: Barra de pan
                  description:
                    type: string
                    description: Descripcion
                    example: "Barra de pan artesana"
                  precio:
                    type: number
                    description: precio
                    example: 1.50€
                  unidades:
                    type: number
                    description: unidades
                    example: 3
                  stock:
                    type: number
                    description: disponibilidad
                    example: true      
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
    post:
      tags:
        - Almacen
      summary: Crearemos un producto en la tabla.
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: 
                - name
                - descripcion
                - precio
                - unidades
              properties:
                name:
                  type: string
                descripcion:
                  type: string
                precio:
                  type: string
                unidades:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Producto creado
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
    delete:
      tags:
        - Almacen
      summary: Eliminaremos todos los productos de la tabla.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Producto eliminado
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
  /producto/{id}:
    get:
      tags:
        - Almacen
      summary: Veremos el producto con un ID determinado.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          description: Id del producto
          required: true
          schema:
            type: integer
            items:
              type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: number
                    description: Id
                    example: 1
                  name:
                    type: string
                    description: Nombre del producto
                    example: Barra de pan
                  description:
                    type: string
                    description: Descripcion
                    example: "Barra de pan artesana"
                  precio:
                    type: number
                    description: precio
                    example: 1.50€
                  unidades:
                    type: number
                    description: unidades
                    example: 3
                  stock:
                    type: number
                    description: disponibilidad
                    example: true    
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor 
    delete:
      tags:
        - Almacen
      summary: Eliminaremos un producto con un ID determinado.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          description: Id del producto
          required: true
          schema:
            type: integer
            items:
              type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Producto eliminado
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor               
  /incrementar-producto:
    put:
      tags:
        - Almacen
      summary: Incrementaremos en uno todas las unidades de los productos.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: number
                    description: Id
                    example: 1
                  name:
                    type: string
                    description: Nombre del producto
                    example: Barra de pan
                  description:
                    type: string
                    description: Descripcion
                    example: "Barra de pan artesana"
                  precio:
                    type: number
                    description: precio
                    example: 1.50€
                  unidades:
                    type: number
                    description: unidades
                    example: 4
                  stock:
                    type: number
                    description: disponibilidad
                    example: true      
        '201':
          description: Creado
          content:
            application/json:
              schema:
                type: string
                example: Creado
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
  /decrementar-producto:
    put:
      tags:
        - Almacen
      summary: Decrementaremos en uno todas las unidades de los productos.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: number
                    description: Id
                    example: 1
                  name:
                    type: string
                    description: Nombre del producto
                    example: Barra de pan
                  description:
                    type: string
                    description: Descripcion
                    example: "Barra de pan artesana"
                  precio:
                    type: number
                    description: precio
                    example: 1.50€
                  unidades:
                    type: number
                    description: unidades
                    example: 2
                  stock:
                    type: number
                    description: disponibilidad
                    example: true      
        '201':
          description: Creado
          content:
            application/json:
              schema:
                type: string
                example: Creado
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
  /incrementar-producto/{id}:
    put:
      tags:
        - Almacen
      summary: Incrementaremos las unidades que queramos de un producto con un ID determinado.
      security:
        - ApiKeyAuth: []
      parameters:
          - name: id
            in: path
            description: ID del producto
            required: true
            schema:
              type: integer
              items:
                type: number
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: 
                - unidades
              properties:
                unidades:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: number
                    description: Id
                    example: 1
                  name:
                    type: string
                    description: Nombre del producto
                    example: Barra de pan
                  description:
                    type: string
                    description: Descripcion
                    example: "Barra de pan artesana"
                  precio:
                    type: number
                    description: precio
                    example: 1.50€
                  unidades:
                    type: number
                    description: unidades
                    example: 4
                  stock:
                    type: number
                    description: disponibilidad
                    example: true      
        '201':
          description: Creado
          content:
            application/json:
              schema:
                type: string
                example: Creado
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor
  /decrementar-producto/{id}:
    put:
      tags:
        - Almacen
      summary: Incrementaremos las unidades que queramos de un producto con un ID determinado.
      security:
        - ApiKeyAuth: []
      parameters:
          - name: id
            in: path
            description: ID del producto
            required: true
            schema:
              type: integer
              items:
                type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: 
                - unidades
              properties:
                unidades:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: number
                    description: Id
                    example: 1
                  name:
                    type: string
                    description: Nombre del producto
                    example: Barra de pan
                  description:
                    type: string
                    description: Descripcion
                    example: "Barra de pan artesana"
                  precio:
                    type: number
                    description: precio
                    example: 1.50€
                  unidades:
                    type: number
                    description: unidades
                    example: 4
                  stock:
                    type: number
                    description: disponibilidad
                    example: true     
        '201':
          description: Creado
          content:
            application/json:
              schema:
                type: string
                example: Creado
        '204':
          description: Sin contenido
          content:
            application/json:
              schema:
                type: string
                example: Sin contenido
        '404':
          description: Página no encontrada
          content:
            application/json:
              schema:
                type: string
                example: Página no encontrada
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: string
                example: Error interno del servidor